management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         enabled: true
         show-details: always
      beans:
         enabled: true
      info:
         enabled: true
      shutdown:
         enabled: true
   server:
      port: '12001'
      address : localhost
spring:
   jpa:
      generate-ddl: 'false'
      properties:
         hibernate:
            use_sql_comments: 'true'
            format_sql: 'true'
      hibernate:
         ddl-auto: none
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: 'true'
      open-in-view: 'false'
   thymeleaf:
      cache: 'false'
      prefix: classpath:/templates/
      check-template-location: 'true'
      suffix: .html
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      password: 1234
      username: poly
      url: jdbc:mariadb://192.168.59.128:3306/myDB
   application:
      name: NOTICE-SERVICE
   boot:
      admin:
         client: # Spring Boot Actuator Admin UI Server
            url: http://localhost:15000

server:
   port: '12000'
